### PR TITLE
Add ClearScreen operation on Ctrl+L

### PR DESCRIPTION
**Pull request by soudy**
Regarding issue #55, I implemented clear screen and bound it to Ctrl+L. I have tested it on Linux , but not on Windows as I have no access to a Windows machine atm.

### CODE REVIEW

**Comment by chzyer** [comment]
Hi! 
Maybe we can clear screen without external commands, just using escape sequences in *nix or syscall in windows. For example, we can use `\033[H` to moves the cursor to (0, 0) ([reference](http://ascii-table.com/ansi-escape-sequences.php)).

In windows, there has a [`ANSI Parser`](https://github.com/chzyer/readline/blob/master/ansi_windows.go) to parse escape sequences to syscalls. So it needs to translate `\033[H` to some api found in [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682073(v=vs.85).aspx), all the windows apis wrapped in [windows_api](https://github.com/chzyer/readline/blob/master/windows_api.go)

Tips: You can ignore the windows part, just label it in README :)

**Comment by soudy** [comment]
@chzyer Hi, thanks for the feedback. I agree it's better to do it without external commands, but the hassle of implementing win32 scared me off, but it seems you already did most of that.

I have a commit coming on its way, and I'll get to a windows machine to test it.

**Comment by soudy** [comment]
Just tested on Windows and works fine

**Comment by chzyer** [comment]
cool 👍

**Pull request merged**
