### PR TITLE
support unique edit line

### LINKED ISSUE #26: [Question] Prevent readline to print.
I'm currently working on a CLI client for a chat application and I really like how this library manipulates the log output. There is currently besides this library no Go library available that refreshes the stdout without including all kinds of lay-outing I do not need.

But I have a question: Is it possible to prevent Readline() from printing to the terminal output?
Currently my output looks like this

> (INSERT) > test
2016/02/14 15:59:07 > Rivalo > test

Where `(INSERT) >` is the prompt for reading the line, and the next line simply returns the sent message inside the chat channel.
I want to prevent the User's message from displaying twice but keep the consistency with the messages from others, which means that after a `\n` readline() shouldn't print its just received line to the stdout.

Is there currently an option or workaround for this I'm overlooking in the documentation? 
(Please, in future, add comments above exported functions, it makes the godoc documentation easier to read)

### PR DESCRIPTION
**Pull request by chzyer**
fixed #26

### CODE REVIEW

**Comment by chzyer** [comment]
@Rivalo I haven't test it well, but it works.

**Comment by Rivalo** [comment]
Cool thank you very much!
Will test it later this day, so I'll fork it so you don't have to maintain this feature :smiley:

**Comment by chzyer** [comment]
@Rivalo OK, please let me know if you have any progress

**Comment by Rivalo** [comment]
@chzyer It works great! Thank you!

**Comment by Rivalo** [comment]
Are you by the way planning to keep this function inside the library? If not (which I can understand, it is also not a part of the GNU Readline library, I think), I'll try to maintain a fork with the functionality and keep it as close to the master as possible.

**Comment by chzyer** [comment]
@Rivalo 
Of course it will(＾ｰ^)ノ

**Pull request merged**
