### PR TITLE
Dynamic autocompletion

### PR DESCRIPTION
**Pull request by setnicka**
I implemented dynamic autocompletion mechanism.

Now there is a new item type "PcItemDynamic" which takes function as
parameter.

When it comes to autocomplete at this position, the function is called,
the whole line is given to it (for example if autocompletion depend on
previous autocompleted field) and functio should return possible strings
how to continue.

Example usage:
 * listing some dynamic key-value storage
 * listing files in directory

### CODE REVIEW

**Comment by setnicka** [comment]
Tested on Debian 5.4.0-3 and Win10, it seems working fine :-)

**Comment by chzyer** [comment]
@setnicka 
I think we should use a new interface for backward compatibility?

**Comment by setnicka** [comment]
@chzyer 
Yes, it would be better. But this will probably yields to duplicate almost every function in completer_helper.go (because we will need to have old version od PrefixCompleter struct and new DynamicPrefixCompleter struct).

Or have you better idea?

**Comment by chzyer** [comment]
Hi! @setnicka , sorry for the lated reply.
How about this:
```go
type DynamicPrefixCompleterInterface interface {
  	PrefixCompleterInterface
	IsDynamic() bool
	GetDynamicNames(line []rune) [][]rune
}
```
In function `Do`, we just assert whether `PrefixCompleterInterface ` is `DynamicPrefixCompleterInterface`.
And please add a new function instead of changing the declaration of `Do`.  :)
Thanks!

**Comment by chzyer** [comment]
BTW, Dynamic autocompletion is really a very cool feature!

**Comment by setnicka** [comment]
Sorry for lated reply too (summer trips, camps, etc).

I added `DynamicPrefixCompleterInterface` like you suggested and yes, it looks good for me now :-)

Plus I split `Do` function into `doInternal` with added parameter and original `Do` with the same declaration.

**Comment by setnicka** [comment]
Is there something I should fix/modify, or it can be merged?

**Comment by chzyer** [comment]
Not yet. Sorry about that. 
I just want to review the code more deeply, I will got some time at weekend :)

**Comment by setnicka** [comment]
Ok, it's fine, thank you :-)

**Comment by chzyer** [comment]
👍 It looks very cool!

**Comment by gotwarlost** [comment]
There is a lot of cool stuff in this code that I wish the docs would explain and give examples for. Every time I think I need something, I come across a type that already seems to do it (fair warning: I have exactly 1 day exposure to this code).

I'll figure out what everything does (eventually :)  - there is a lot of stuff). Would you be open to accepting a PR with godoc additions and examples only?

**Comment by chzyer** [comment]
@gotwarlost 
That's welcome :)

**Pull request merged**
